### PR TITLE
fixed typo in threshold and quoram section of onchain multisig guide

### PR DESCRIPTION
**Pull request by pratikpatil2001**
Screenshot from 2024-10-25 10-27-15

### CODE REVIEW

**Comment by julienrbrt** [comment]
Hey, thank you! Please open a PR on the SDK to fix an issue

**Comment by pratikpatil2001** [comment]
I don't find the repo on cosmos SdK it's in docs right??? It isn't fixed?

**Comment by julienrbrt** [comment]
Yes, you need to open an issue on the cosmos-sdk repo directly, this repo simply handles the building

**Comment by pratikpatil2001** [comment]
You mean I'll have to reopen same issue on cosmos SdK!
Okay ! Thanks

**Pull request closed without merging**
