### PR TITLE
refactor: update script with build

### PR DESCRIPTION
**Pull request by samricotta**

### CODE REVIEW

**Comment by julienrbrt** [comment]
What's the reason of this change?

**Comment by samricotta** [comment]
What we discussed in slack, running the pre and post is needed so we can copy and delete files? Maybe I misunderstood.

**Comment by julienrbrt** [comment]
That's correct, but you just need to call the script, there is no js in the cosmos-sdk repo anymore.

**Comment by julienrbrt** [comment]
Btw, the condition in https://github.com/cosmos/cosmos-sdk-docs/pull/44/files#diff-256551fe1e5b7491e6f1d013256b8a827d03827ed7f6df2c09f7de392119b087R53-R61 does the same thing, is that intended?

**Comment by tac0turtle** [comment]
fixing this here https://github.com/cosmos/cosmos-sdk-docs/pull/46

**Pull request closed without merging**
