### PR TITLE
refactor: update to main docs w changes

### PR DESCRIPTION
**Pull request by samricotta**
script changes, not sure if we should let the script run them but here they also are maybe if we want to compare

### CODE REVIEW

**Comment by tac0turtle** [comment]
why not let the script run this?

**Comment by samricotta** [comment]
Yeahh thats why i mentioned in the description its kinda redundant but we can leave them here and see if they update correctly

**Comment by tac0turtle** [comment]
https://github.com/cosmos/cosmos-sdk-docs/actions/runs/6179138879/job/16773575787 

update failed

**Comment by samricotta** [comment]
Ill look at adjusting the branch protection rules then, looks like it is an issue when pushing to main

**Comment by tac0turtle** [comment]
it shouldnt push to main, it should create a pr so we can verify the changes

**Comment by samricotta** [comment]
okay then a PR beforehand then?

**Pull request closed without merging**
