### PR TITLE
refactor: Learn updates outside of versioning

### PR DESCRIPTION
**Pull request by samricotta**
Updates develop to learn for docusaurus file and other various config files

### CODE REVIEW

**Comment by samricotta** [comment]
Failures will be corrected once https://github.com/cosmos/cosmos-sdk-docs/pull/45 is merged

**Review by julienrbrt — COMMENTED** [review]
ACK, but https://github.com/cosmos/cosmos-sdk-docs/pull/45 should be merged first.

**Review by julienrbrt — APPROVED** [review]
ACK, but https://github.com/cosmos/cosmos-sdk-docs/pull/45 should be merged first.

**Comment by tac0turtle** [comment]
closing in favour of https://github.com/cosmos/cosmos-sdk-docs/pull/51

**Pull request closed without merging**
